/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JLabel;
import napakalaki.CombatResult;
import napakalaki.Napakalaki;

/**
 *
 * @author david
 */
public class NapakalakiView extends javax.swing.JFrame {

    Napakalaki napakalakiModel;
    public static int personaje = 0;
    
    
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }

    public void setNapakalaki(Napakalaki model){
        this.napakalakiModel = model;
        
        this.playerView1.setPlayer(this.napakalakiModel.getCurrentPlayer());
        this.playerView1.setNapakalaki(model);
        
        this.playerView1.setDescartarTesoro(true);
        this.playerView1.setDescartarTodo(true);
        this.playerView1.setMakeVisible(true);
        this.playerView1.setRobar(this.napakalakiModel.getCurrentPlayer().canISteal());
        
        this.monsterView1.setMonster(this.napakalakiModel.getCurrentMonster());
       // this.monsterView1.setOpaque(false);
        this.monsterView1.setVisible(false);
        
        this.mostrarMonstruo.setEnabled(true);
        this.luchar.setEnabled(false);
        this.turno.setEnabled(false);
        
        this.personaje = this.personaje%this.napakalakiModel.getPlayersSize();
        
        
        if(this.personaje == 0){
                this.person.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenesNapakalaki/bulb.png")));
        }else if(this.personaje == 1){
                person.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenesNapakalaki/cha.png")));
        }else if(this.personaje == 2){
                person.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenesNapakalaki/squ.png")));
        }
        
        this.personaje++;
        
        this.pend.setEnabled(false);
        
        setVisible(true);
        
        repaint();
        revalidate();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        error = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        noTurn = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        win = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pendingCon = new javax.swing.JScrollPane();
        pend = new javax.swing.JTextArea();
        mostrarMonstruo = new javax.swing.JButton();
        luchar = new javax.swing.JToggleButton();
        combate = new javax.swing.JLabel();
        monsterView1 = new GUI.MonsterView();
        turno = new javax.swing.JButton();
        person = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        playerView1 = new GUI.PlayerView();

        error.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        error.setLocation(new java.awt.Point(100, 50));
        error.setMinimumSize(new java.awt.Dimension(400, 100));
        error.setSize(new java.awt.Dimension(400, 100));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No has cumplido tu Pending Bad Consequence");

        noTurn.setText("OK");
        noTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTurnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout errorLayout = new javax.swing.GroupLayout(error.getContentPane());
        error.getContentPane().setLayout(errorLayout);
        errorLayout.setHorizontalGroup(
            errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        errorLayout.setVerticalGroup(
            errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noTurn)
                .addContainerGap())
        );

        win.setText("Has ganau");

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(win, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(win, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(1, 1, 1));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(1, 1, 1));
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1368, 768));
        getContentPane().setLayout(null);

        pend.setColumns(20);
        pend.setRows(5);
        pendingCon.setViewportView(pend);

        getContentPane().add(pendingCon);
        pendingCon.setBounds(490, 90, 350, 130);

        mostrarMonstruo.setText("Mostrar bicho");
        mostrarMonstruo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarMonstruoActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarMonstruo);
        mostrarMonstruo.setBounds(130, 46, 200, 29);

        luchar.setText("Combatir");
        luchar.setMinimumSize(new java.awt.Dimension(80, 32));
        luchar.setPreferredSize(new java.awt.Dimension(80, 32));
        luchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lucharActionPerformed(evt);
            }
        });
        getContentPane().add(luchar);
        luchar.setBounds(130, 90, 200, 30);

        combate.setFont(new java.awt.Font("Pokemon Pixel Font", 0, 24)); // NOI18N
        getContentPane().add(combate);
        combate.setBounds(490, 30, 350, 40);
        getContentPane().add(monsterView1);
        monsterView1.setBounds(920, 10, 252, 405);

        turno.setText("Pasar turno");
        turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnoActionPerformed(evt);
            }
        });
        getContentPane().add(turno);
        turno.setBounds(130, 130, 200, 30);
        getContentPane().add(person);
        person.setBounds(130, 210, 340, 200);

        back.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenesNapakalaki/ccc.png"))); // NOI18N
        back.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        back.setAlignmentY(0.0F);
        getContentPane().add(back);
        back.setBounds(0, 0, 1366, 420);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1361, 0, 8, 778);
        getContentPane().add(playerView1);
        playerView1.setBounds(-4, 411, 1368, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lucharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lucharActionPerformed
        
        this.luchar.setEnabled(false);
        
        CombatResult cr = this.napakalakiModel.developCombat();
        this.combate.setText("Resultado combate:    " + this.napakalakiModel.developCombat().toString());
        
        if (cr == CombatResult.LOSE || cr == CombatResult.LOSEANDCONVERT){
            this.napakalakiModel.getCurrentPlayer().setPendingBadConsequence(
                napakalakiModel.getCurrentMonster().getBadConsequence().adjustToFitTreasureList(
                napakalakiModel.getCurrentPlayer().getVisibleTreasures(),
                napakalakiModel.getCurrentPlayer().getHiddenTreasures() ));
        }else if ( cr == CombatResult.WINGAME){
            this.win.setText("¡El jugador " + this.napakalakiModel.getCurrentPlayer().getName() + " ha ganado!");
        
        }
        
        if(this.napakalakiModel.getCurrentPlayer().getPendingBad() != null){
            this.pend.setEnabled(true);    
            this.pend.setText("Pending Bad Consequence:  " + this.napakalakiModel.getCurrentPlayer().getPendingBad().toString());
            
        }else{ 
            this.pend.setText("");
        }
        
        this.playerView1.setPlayer(this.napakalakiModel.getCurrentPlayer());
        this.playerView1.setDescartarTesoro(true);
        this.playerView1.setDescartarTodo(true);
        this.playerView1.setMakeVisible(true);
        
        this.pend.setEditable(false);
        
      //  if(this.napakalakiModel.nextTurnAllowed())
            this.turno.setEnabled(true);
        
    }//GEN-LAST:event_lucharActionPerformed

    private void mostrarMonstruoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarMonstruoActionPerformed
        this.mostrarMonstruo.setEnabled(false);
        
        this.luchar.setEnabled(true);
        
        this.monsterView1.setMonster(this.napakalakiModel.getCurrentMonster());
        this.monsterView1.setOpaque(true);
        this.monsterView1.setVisible(true);
        
        this.playerView1.setMakeVisible(false);
        
    }//GEN-LAST:event_mostrarMonstruoActionPerformed

    private void turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnoActionPerformed
     
        if(this.napakalakiModel.nextTurn()){

            this.pend.setText("");
            this.pend.setEnabled(false);
            
            this.combate.setText("Resultado combate:");
            
            this.playerView1.setMakeVisible(true);
            this.playerView1.setDescartarTesoro(false);
            this.playerView1.setDescartarTodo(false);

            this.monsterView1.setEnabled(false);
            
            this.setNapakalaki(napakalakiModel);
            this.turno.setEnabled(false);
            
        }else{
            this.error.setVisible(true);
            this.error.setEnabled(true);
            this.playerView1.setPlayer(this.napakalakiModel.getCurrentPlayer());
        }
        
        
        repaint();
    }//GEN-LAST:event_turnoActionPerformed

    private void noTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTurnActionPerformed
        this.error.setVisible(false);
        this.error.setEnabled(false);
        this.turno.setEnabled(true);
        
        this.playerView1.setPlayer(this.napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_noTurnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    
    public void showView(){
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel combate;
    private javax.swing.JDialog error;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton luchar;
    private GUI.MonsterView monsterView1;
    private javax.swing.JButton mostrarMonstruo;
    private javax.swing.JButton noTurn;
    private javax.swing.JTextArea pend;
    private javax.swing.JScrollPane pendingCon;
    private javax.swing.JLabel person;
    private GUI.PlayerView playerView1;
    private javax.swing.JButton turno;
    private javax.swing.JLabel win;
    // End of variables declaration//GEN-END:variables
}
